////////////////////
// class forwards //
////////////////////

#ifndef __PTC_CLASSES_H_
#define __PTC_CLASSES_H






// ptc classes
class Interface;
class IDummy;
class ISoftware;
class IVGA;
class IVESA;
class IWin32;
class IGDI;
class IDirectX;
class Surface;
class Palette;
class FORMAT;
class COLOR;
class CONVERTER;
class RECTANGLE;
class PTC;
class MemoryBlock;
class MemoryManager;

// ptc structs
struct EFFECTS;
struct MODE;






#endif
