//////////////////////////////////////
// 16bit -> X conversion (ansi c++) //
//////////////////////////////////////
#include "cpp_16.h"








#if defined(__16BIT__)


void Convert16_ARGB8888_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_ABGR8888_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_RGBA8888_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_BGRA8888_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_RGB888_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_BGR888_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_BGR565_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_ARGB1555_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_ABGR1555_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_GREY8_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


void Convert16_RGB332_CPP(void *src,void *dest,uint pixels,void *extra)
{
    // advoid warnings
    if (src || dest || pixels || extra);
}


#endif
